import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={"h-full m-0"} lang="en">
      <body className={"h-full m-0"}>{children}</body>
    </html>
  );
}
